### ISSUE TITLE
Sumologic Logs into Kubernetes XNAT

### ISSUE THREAD

**Issue by mirestrepo** [brown-bnc/roadmap#11]
- [x] Reintegrate SumoLogics into sidecar 
- [x] Deploy SumoLogics in separate container
- [x] Remove SumoLogics from sidecar
- [x] Verify error logs reported from container service

**Comment by mirestrepo** [comment]
- [x] Decide, look into encryption of logs and whether that's needed - Sumologic encrypts at rest. Transition uses HTTPS
