### ISSUE TITLE
Address XNAT (bke) stability issues

### ISSUE THREAD

**Issue by mirestrepo** [brown-bnc/roadmap#12]
Investigate and adress 504 responses

**Comment by fordmcdonald** [comment]
Blocked by
- [ ] #10

**Comment by mirestrepo** [comment]
- [ ] Many connections open at once - xnat_tools python script from oscar. Data TBD
- [ ] Heavy DICOM upload
- [ ] Database problems - also may lead t data recovery from DB 
- [ ] Multiple user connections?
- [ ] Authentication issues
- [ ] Simultaneous operations
- [ ] Timeouts
