### ISSUE TITLE
Build a motion correction task with HoneyComb

### ISSUE THREAD

**Issue by mirestrepo** [brown-bnc/roadmap#13]
- [ ] Build prototype in JSPsych code sandbox
- [ ] Investigate JSPsych serial plugins
- [ ] Create forked repository from Honeycomb
- [ ] Create project issues by scope
