### ISSUE TITLE
CCV Bootcamp XNAT Workshop Prep

### ISSUE THREAD

**Issue by fordmcdonald** [brown-bnc/roadmap#31]
- [ ] Test run_xnat2bids script / xnat2bids pipeline
- [ ] Update slides / graphics 
- [ ] Send notice to registered participants
