### ISSUE TITLE
Migrate XNAT from SciDMZ to BKE

### ISSUE THREAD

**Issue by fordmcdonald** [brown-bnc/roadmap#35]
Currently XNAT is deployed in the science dmz BKE, which was orignally created so we could share filesystem with Oscar. The science DMZ cluster is only used by our team and often is a bit behind in features and maintainance cycle when compared to production BKE. For example we don't have the auto renew SSL feature. Moving XNAT to production BKE is now possible if we store data in the research partition of VAST (files22.brown.edu/Research). If XNAT (and ConstructDB) move out of the ScienceDMZ cluster, Tom can get rid of that cluster. Less work for him, more features for us

- [x] Meeting with Tom
- [x] Create XNAT folder in files22
- [x] Request new cluster, prod/qa namespaces
- [ ] New Firewall rules for databases
- [ ] Deploy prod/qa
- [ ] Test AutoSSH from MRF to BKE
- [ ] Transfer HAProxy timeout server settings
- [ ] Tests functionality before data transfer
- [ ] Rsync data from TrueNAS -> files22

**Comment by fordmcdonald** [comment]
11/26 Meeting Notes with Tom:

- Tom will add a research node for XNAT and set up storage classes.
- HAProxy changes will need to be transferred to BKE LTM (local traffic manager).  Suspects no issues with large transfers. 
- Plan to coordinate IP subnets for QA / Prod Postgres DB firewalls.
- Tom is confident we can get AutoSSH to work, will test once namespaces have been created on the cluster.  
- Coincides with effort to migrate scidmz from VMWare to HyperV, will pause.
- Component of Rancher is being deprecated, requires rebuild and redeployment of all BKE deployments to new clusters.  
- I will make request for prod / qa namespaces on BKE.
- @mirestrepo Does this rise to the level of a "project", or is this effort "operational"?
